### ISSUE TITLE
How to modify the code if  the ligand of my system interactive with other molecules such as magnesium ion besides protein?

### ISSUE THREAD

**Issue by wyq87** [rostaresearch/unbinding#2]
In my system,the ligand interactive with other molecules such as magnesium ion.However,your code only consider the situation that ligand only interactive with the protein. I try to modify the code(I motified the line 62: ` protein = self.prevtraj.top.select("(protein or resname MG GDP) and not type H")` in the file `src/read_pdb.py`),but entry `centers ` and `targetCenters` in the file `sum_1.col` is `nan`, and it reported the error:
 ```
/gpfs/home/fxia/software/unbinding-main/src/CoM_colvars.py:32: RuntimeWarning: invalid value encountered in true_divide
  return np.sum(massWeighted, axis=0) / np.sum(self.masses)
```
Would you please help me take a look?

**Comment by Cynthia0807-learn** [comment]
I also have a quesion: Iine 102-118 of file `src/scr3_python_colvar_generator.py `, it seems that some types of amino acid are lost.Why?

**Comment by Cynthia0807-learn** [comment]
the first problem was solved.but I am still confused to the second problem.

**Comment by wyq87** [comment]
There's something wrong with my input file.The problem was solved
